- name: Update Maven build options (add productized profile)
  ansible.builtin.command:
    cmd: >
      bash {{ script_file }} {{ workflow_file }} '{{ selector }}' {{ key }} '{{ value }}'
  register: update_result
  changed_when: "'Appending' in update_result.stdout"
  check_mode: no
  vars:
    workflow_file: "{{ cloning_target_dir }}/{{ item.location }}"
    selector: '{{ item.yq_selector_path }}'
    script_file: "{{ role_path }}/../common/files/yaml_update__create_key_or_extend_existing_one.sh"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { location: "kie-tools/.github/actions/setup-maven-cache/action.yml",
        key: "MAVEN_OPTIONS",
        value: "-Dproductized",
        yq_selector_path: '.runs.steps[] | select(.name=="Clone and Build Drools, Runtimes and Apps repositories").env'
    }

- name: Commit - Update Maven build options (add productized profile)
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/commit_changes_if_any.yml"
  vars:
    repository_folder_location: "{{ repository_location }}"
    commit_message: "Add productized profile"
