# TODO: !!! KOGITO_RUNTIME_version - my comment 3.c in OSL Productization cut‐off process
# TODO: !!! QUARKUS_PLATFORM_version - my comment 3.d in OSL Productization cut‐off process
- name: Update index.js files OSL__branchName (3.a) + KIE_TOOLS_BUILD__streamName (3.b) + KOGITO_RUNTIME_version (3.c) + QUARKUS_PLATFORM_version???????
  replace:
    path: "{{ repository_location }}/{{ file_path }}"
    regexp: "{{ item.the_regexp }}"
    replace: "{{ item.the_replace}}"
  vars:
    file_path: "packages/root-env/env/index.js"
  loop:
    - { file_path: "packages/redhat-env/env/index.js", "the_regexp": 'default:\s*"[^"]*"', "the_replace": 'default: "{{ product_version_short }}"' }
    - { file_path: "packages/root-env/env/index.js", "the_regexp": '(\s*KIE_TOOLS_BUILD__streamName:\s*{\s*default:\s*")[^"]+(")', "the_replace": '\g<1>{{ product_version }}\g<2>' }
    - { file_path: "packages/root-env/env/index.js", "the_regexp": '(\s*KOGITO_RUNTIME_version:\s*{\s*default:\s*")[^"]+(")', "the_replace": '\g<1>{{ kogito_version }}\g<2>' }
  loop_control:
    loop_var: item

# TODO: JS validation here

- name: Commit - Update index.js files
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/commit_changes_if_any.yml"
  vars:
    repository_folder_location: "{{ cloning_target_dir }}/{{ item.midstream | basename }}"
    commit_message: "Update supporting-files (ci/osl/.env)"
  loop: "{{ kie_tool_repositories }}"
  loop_control:
    label: "{{ item.midstream }}"
