- name: Update version pom.xml and README files
  ansible.builtin.shell: |
    find . \( -iname "pom.xml" -o -iname "README.md" \) -print0 | xargs -0 sed -i "s/>{{ snapshot_version }}</>{{ kogito_version }}</g"
  args:
    chdir: "{{ cloning_target_dir }}/{{ item.midstream | basename }}"
  loop: "{{ repositories }}"
  loop_control:
    label: "{{ item.midstream }}"


### TODO: after pom.xml update we need to verify it
# - neither now
# - or later in the CI after commit + push

- name: Commit - Update version pom.xml and README files
  include_tasks: commit_changes_if_any.yml
  vars:
    repository_folder_location: "{{ cloning_target_dir }}/{{ item.midstream | basename }}"
    commit_message: "Update version from {{ snapshot_version }} to {{ kogito_version }} in pom.xml files"
  loop: "{{ repositories }}"
  loop_control:
    label: "{{ item.midstream }}"
