- name: Synchronize branches, sync optionally and create new release branches
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/clone_repositories_sync_optionally_and_checkout_release_branch.yml"
  vars:
    repositories: "{{ osl_images_repositories }}"

- name: Update all pom.xml files (apps-maven-builder)
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/update_snapshot_version_in_pom_files_with_new_release_version.yml"
  vars:
    repositories: "{{ osl_images_repositories }}"

- name: Update versions in osl images
  include_tasks: update_product_versions_in_osl_images.yml
  vars:
    osl_images_repository_location: "{{ cloning_target_dir}}/{{ osl_images_repositories[0].midstream | basename }}"
    file_name_pattern: "*.yaml"
    to_find: '999.0.0.main'
    replacement: "{{ osl_image_tag }}"
    excluded_dirs:
      - images-dist

- name: Update branch names in operator image
  include_tasks: update_branch_names_in_operator_image.yml
  vars:
    osl_images_repository_location: "{{ cloning_target_dir}}/{{ osl_images_repositories[0].midstream | basename }}"

- name: Update versions in images
  include_tasks: update_versions_in_images.yml
  vars:
    osl_images_repository_location: "{{ cloning_target_dir}}/{{ osl_images_repositories[0].midstream | basename }}"

- name: Update versions in images modules
  include_tasks: update_versions_in_images_modules.yml
  vars:
    osl_images_repository_location: "{{ cloning_target_dir}}/{{ osl_images_repositories[0].midstream | basename }}"


- name: Update quarkus versions
  include_tasks: update_quarkus_versions.yml
  vars:
    osl_images_repository_location: "{{ cloning_target_dir}}/{{ osl_images_repositories[0].midstream | basename }}"

- name: Push branches to remote
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/push_repo.yml"
  vars:
    repository_folder_location:  "{{ cloning_target_dir }}/{{ item.midstream | basename }}"
  loop: "{{ osl_images_repositories }}"
  loop_control:
    label: "{{ item.midstream }}"