- name: Update update_kogito_project_versions
  ansible.builtin.command:
    cmd: >
      bash {{ script_file }} '{{ file_location }}' '{{ selector }}' {{ key }} '{{ value }}'
  register: update_result
  changed_when: "'Appending' in update_result.stdout"
  check_mode: no
  vars:
    file_location: "{{ repository_folder_location }}/{{ file_path }}"
    selector: "{{ item.yq_selector_path }}"
    property: '{{ item.property }}'
    script_file: "{{ role_path }}/../common/files/yaml_update__ensure_key_and_vaue_exist.sh"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
    file_path: "images-dist/modules/kogito-project-versions/module.yaml"
  loop:
    - { key: "value",
        value: "{{ quarkus_group_id }}",
        yq_selector_path: '.envs[] | select(.name=="QUARKUS_PLATFORM_GROUPID")'
    }
    - { key: "value",
        value: "{{ quarkus_platform_version }}",
        yq_selector_path: '.envs[] | select(.name=="QUARKUS_PLATFORM_VERSION")'
    }
    - { key: "value",
        value: "{{ quarkus_version }}",
        yq_selector_path: '.envs[] | select(.name=="QUARKUS_VERSION")'
    }
    - { key: "version",
        value: "{{ kogito_version }}",
        yq_selector_path: '-'
    }

- name: Commit - update_kogito_project_versions
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/commit_changes_if_any.yml"
  vars:
    repository_folder_location: "{{ cloning_target_dir }}/{{ item.midstream | basename }}"
    commit_message: "Update kogito project versions"
  loop: "{{ osl_images_repositories }}"
  loop_control:
    label: "{{ item.midstream }}"
