- name: Determine SHA1 of the respective HEAD in the kie tools repository
  ansible.builtin.shell:
    # -q v grepu zajistí, že hledáme přesnou shodu pro HEAD na konci řádku
    git ls-remote {{ kie_tools_repository }} HEAD | awk '{print $1}'
  register: kie_tools_repository_head_ref_result

- ansible.builtin.set_fact:
    # reference (i.e. commit) to source code of kubesmarts/kie-tools (update rhel operator image)
    kie_tools_repository_head_ref: "{{ kie_tools_repository_head_ref_result.stdout | trim }}"

- name: Update manifests - 1) branch names for OSBS and 2) reference to source code of kubesmarts/kie-tools
  ansible.builtin.command:
    cmd: >
      bash {{ script_file }} '{{ file_location }}' '{{ selector }}' {{ key }} '{{ value }}'
  register: update_result
  changed_when: "'Appending' in update_result.stdout"
  check_mode: no
  vars:
    file_location: "{{ repository_folder_location }}/{{ item.file_path }}"
    selector: "{{ item.yq_selector_path }}"
    property: '{{ item.property }}'
    script_file: "{{ role_path }}/../common/files/yaml_update__ensure_key_and_vaue_exist.sh"
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - { file_path: "osl-operator-image/logic-{{ rhel_platform }}-operator-image.yaml",
        key: "ref",
        value: "{{ kie_tools_repository_head_ref }}",
        yq_selector_path: '.[0].osbs.configuration.container.remote_source'
    }
    - { file_path: "osl-operator-image/logic-{{ rhel_platform }}-operator-image.yaml",
        key: "branch",
        value: "{{ osbs_repository_branch }}",
        yq_selector_path: '.[] | select(.name == "openshift-serverless-1/logic-{{ rhel_platform }}-operator") | .osbs.repository'
    }
    - { file_path: "osl-cli-artifacts-image/logic-kn-workflow-cli-artifacts-{{ rhel_platform }}-image.yaml",
        key: "branch",
        value: "{{ osbs_repository_branch }}",
        yq_selector_path: '.[] | select(.name == "openshift-serverless-1/logic-kn-workflow-cli-artifacts-{{ rhel_platform }}") | .osbs.repository'
    }

- name: Commit - Update manifests - 1) branch names for OSBS and 2) reference to source code of kubesmarts/kie-tools
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/commit_changes_if_any.yml"
  vars:
    repository_folder_location: "{{ cloning_target_dir }}/{{ item.midstream | basename }}"
    commit_message: "Update manifests - 1) branch names for OSBS and 2) reference to source code of kubesmarts/kie-tools"
  loop: "{{ osl_images_repositories }}"
  loop_control:
    label: "{{ item.midstream }}"
