  - name: Find all yaml files except excluded directories
    ansible.builtin.find:
      paths: "{{ osl_images_repository_location }}"
      patterns: "{{ file_name_pattern }}"
      recurse: yes
      excludes: "{{ excluded_dirs }}"
    register: yaml_files

  - name: Replace version string in yaml files
    ansible.builtin.replace:
      path: "{{ item.path }}"
      regexp: "{{ to_find }}"
      replace: "{{ replacement }}"
    loop: "{{ yaml_files.files }}"

  - name: Commit - Update versions in operator modules
    include_tasks: "{{ playbook_dir }}/roles/common/tasks/commit_changes_if_any.yml"
    vars:
      repository_folder_location: "{{ osl_images_repository_location }}"
      commit_message: "Update versions in operator modules"
    loop: "{{ osl_images_repositories }}"
    loop_control:
      label: "{{ item.midstream }}"
