- name: Synchronize branches and create new release branches
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/synchronize_branches_and_checkout_release_branch.yml"
  vars:
    repositories: "{{ product_repositories }}"

- name: Update all pom.xml files
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/update_pom_files_with_new_version.yml"
  vars:
    repositories: "{{ product_repositories }}"

- name: Remove non-product modules
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/remove_non_product_modules.yml"
  vars:
    repositories: "{{ product_repositories }}"

- name: Update Maven build options - ensure productized profile
  include_tasks: update_maven_build_options.yml
