---
- name: OSL cut-off
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "{{ vars_location | default('defaults.yml') }}"

  vars:
    # override via command line
    cloning_target_dir: "{{ playbook_dir }}/../OUT"
    # override via command line
    sync_with_upstream_enabled: false
    enable_push_to_remote: true

  roles:

    - role: cut_off_products
      vars:
        product_repositories: "{{ cut_off_products.product_repositories }}"

    - role: cut_off_kubesmarts_kie_tools
      vars:
        kie_tools_build__build_container_images: "{{ cut_off_kubesmarts_kie_tools.kie_tools_build__build_container_images }}"
        kie_tool_repositories: "{{ cut_off_kubesmarts_kie_tools.kie_tool_repositories }}"

    - role: cut_off_kubesmarts_osl_images
      vars:
        rhel_version: "{{ cut_off_kubesmarts_osl_images.rhel_version }}"
        rhel_platform: "{{ cut_off_kubesmarts_osl_images.rhel_platform }}"
        osbs_repository_branch: "{{ cut_off_kubesmarts_osl_images.osbs_repository_branch }}"
        osl_image_tag: "{{ cut_off_kubesmarts_osl_images.osl_image_tag }}"
        osl_images_repositories: "{{ cut_off_kubesmarts_osl_images.osl_images_repositories }}"
        kie_tools_repository: "{{ cut_off_kubesmarts_kie_tools.kie_tool_repositories[0].midstream_https }}"

    - role: setup_ci_cogito_pipelines
      vars:
        cogito_pipelines_repository: "{{ setup_ci_cogito_pipelines.repository }}"

    - role: setup_ci_middleware_build_configuration
      vars:
        middleware_build_configuration_repository: "{{ setup_ci_middleware_build_configuration.repository }}"

    - role: setup_ci_kie_ci
      vars:
        kie_cie_repository: "{{ setup_ci_kie_ci.repository }}"
