---
- name: OSL cut-off
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cloning_target_dir: "{{ playbook_dir }}/OUT"
    snapshot_version: "999-SNAPSHOT"
    product_version: "1.37.0"
    product_version_short: "1.37"
    kogito_version: "9.104.0"
    branch_name: "{{ 9.104 }}.x-prod"

    quarkus_version: '${QUARKUS_VERSION:3.20.1}' # The quarkus version is clarified while CUT off starts. We should take the latest version available from RHBQ releases
    kogito_images_cekit_modules__quarkus_group_id: "com.redhat.quarkus.platform"
    kie_tools_build__build_container_images: "false"
  roles:
    - role: cut_off_products
      vars:
        product_repositories:
          - { midstream: "git@github.com:kiegroup/kogito-apps", upstream: "git@github.com:apache/incubator-kie-kogito-apps" }
          - { midstream: "git@github.com:kiegroup/drools", upstream: "git@github.com:apache/incubator-kie-drools" }
          - { midstream: "git@github.com:kiegroup/kogito-examples", upstream: "git@github.com:apache/incubator-kie-kogito-examples" }
          - { midstream: "git@github.com:kiegroup/kogito-runtimes", upstream: "git@github.com:apache/incubator-kie-kogito-runtimes" }
    - role: cut_off_kubesmarts_kie_tools
      vars:
        kie_tool_repositories:
          - { midstream: "git@github.com:kubesmarts/kie-tools", upstream: "git@github.com:apache/incubator-kie-tools" }
